### ISSUE TITLE
Display time of last update or time from last refresh

### ISSUE THREAD

**Issue by autarkper** [mockturtl/cinnamon-weather#12]
It would be very helpful to be able to see the time of the last weather update for one's chosen location. Alternatively, you could display how many minutes old the information is. As things are now, one can only hope that the data shown is reasonably up-to-date.

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
