### ISSUE TITLE
About dialog

### ISSUE THREAD

**Issue by zagortenay333** [mockturtl/cinnamon-weather#123]
Could you populate the about dialog with some info? Would be cool.

**Comment by mockturtl** [comment]
@zagortenay333 Can you show me an example?  None of my applets display anything but the description and version.

**Comment by zagortenay333** [comment]
The places/graphic/office center applets do, configurable menu, gpaste, desktop-capture..

**Comment by rjanja** [comment]
@mockturtl see [modalDialog.js::AboutDialog](https://github.com/linuxmint/Cinnamon/blob/master/js/ui/modalDialog.js#L423), there are a couple of additional undocumented keys you can specify in metadata.json which are used for populating this dialog.

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
