### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by chrismatinez81** [mockturtl/cinnamon-weather#14]
ive been using this applet for the past month and its worked great but 2 days ago it stopped working.  ive tried to uninstall and still not working

**Comment by digeomel** [comment]
I'm not sure what is the current status of this, since the last post is from 2012, but I'm still experiencing proxy authentication issues on RHEL 7 with Cinnamon 2.8.8 and the latest version of the Weather applet. If I set the proxy settings to manual, it works fine. When I switch to a wpad automatic script, it fails. Any ideas?

**Comment by mockturtl** [comment]
@digeomel The upstream bug status (https://bugzilla.gnome.org/show_bug.cgi?id=684921) indicates "auto" has the intended behavior.

I don't use or understand GNOME proxying, but it's probably outside the scope of an applet.  You might want to [file an issue with Cinnamon](https://github.com/linuxmint/cinnamon/issues) explaining the observed vs. expected behavior.
