### ISSUE TITLE
The `.weather-menu` class is not applied

### ISSUE THREAD

**Issue by zagortenay333** [mockturtl/cinnamon-weather#175]
Since cinna `3.2` the top menu class `.weather-menu` is not applied. Looks like the method for adding one was changed.

See: https://github.com/linuxmint/Cinnamon/pull/5948/files#diff-9730f14a54367b06bdc5d0af4a9a5706

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
