### ISSUE TITLE
No colors on panel icons

### ISSUE THREAD

**Issue by vpal** [mockturtl/cinnamon-weather#181]
Greetings,

When I uncheck "Symbolic icons" in the configuration the icons on the panel are barely visible very dark and missing colors.
Colors are visible in the forecast window.
I would expect the icons to look like this https://cinnamon-spices.linuxmint.com/git/applets/weather@mockturtl/screenshot.png instead of how they look like here: ![weather-applet-icons](https://cloud.githubusercontent.com/assets/3486417/22377287/9440972e-e4b1-11e6-8e15-33cae09413ff.png)

I'm using Ubuntu based Mint 18. Have the latest update installed from spices.

Thanks

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
