### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by ghost** [mockturtl/cinnamon-weather#64]
There appears to be no way of aligning the text of the conditions with their values!
![secondary_002](https://cloud.githubusercontent.com/assets/5655339/2687024/270bbfdc-c22f-11e3-93d8-9ee188a07159.png)

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
