### ISSUE TITLE
Notification area icon is hardly visible

### ISSUE THREAD

**Issue by iwis** [mockturtl/cinnamon-weather#73]
severity: major
reproducibility: always
category: UI, Usability
os version: Mint Cinnamon 16 and 17, 64-bit (Cinnamon 2.2, 2.0.14)

**Description**: Applet icon in default Mint Cinnamon theme (the theme is named "Linux Mint") is hardly visible:
![applet-weather - default icon](https://cloud.githubusercontent.com/assets/8080496/3554914/888bda66-0911-11e4-9b2f-86c11da337dc.jpg)
The icon is also hardly visible in "Cinnamon" theme. After changing to "Symbolic icons" in applet settings the aforementioned icon looks well:
![applet-weather - symbolic icons](https://cloud.githubusercontent.com/assets/8080496/3554926/b7b1bf36-0911-11e4-86c0-c2774c997924.jpg)

**Suggested solution**: Selecting "Symbolic icons" by default or fixing the default (not symbolic) icon.

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
