### ISSUE TITLE
[UI tweak] Displaying "19°" instead of "19 °C" in notification area

### ISSUE THREAD

**Issue by iwis** [mockturtl/cinnamon-weather#74]
related to: https://github.com/mockturtl/cinnamon-weather/issues/20

It takes a lot of space to display weather icon and current temperature with unit of measurement - about three times more than a standard icon (for example power or network icon). By displaying only "°" instead of " °C"/" °F" we will occupy a space that is normally occupied by only two icons. If one set the unit of measurement, for example to "° F", he should remember which unit of measurement he is using, so displaying the unit of measurement is unnecessary. Furthermore for temperatures greater than 0 °C it is easy to distinguish between the two units. I checked than some programs display only grade symbol without unit: for example my favorite [WeatherMate](http://www.ravib.com/wm/) in Windows. What do you think about this? After all we can display "19°" for Celsius - because it is metric ;) , but "66 °F" for Fahrenheit.

**Comment by deekej** [comment]
Sorry, but I don't like this proposal. I have a Full HD screen, and the space it takes is really not big nor significant for me.

I know I can remember it is set for °C, but since there were few issues with the applet lately, I would have tendencies to often check it if it is still displaying the correct system.

I can imagine this having as an option, but it shouldn't be default behaviour.

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
