### ISSUE TITLE
[trivial] Default options

### ISSUE THREAD

**Issue by iwis** [mockturtl/cinnamon-weather#75]
I would like to have a computer system that can be installed and configured according to my preferences without too many steps that I have to do manually. This is specifically important for Mint because a new version arrives every 6 months and an installation from the beginning is recommended.
Is it good idea to select by default the options that are used by most people? For example if most people set "Show the weather condition" to off, why not set it off by default? For example I always change the following default settings:

```
"Show 5-day forecast": yes
"Show the weather condition": no
```

If the idea is nice then everybody interested can write the settings he is using. People that don't change any settings should write it also otherwise the voting will be biased :)

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
