### ISSUE TITLE
display error message on failure

### ISSUE THREAD

**Issue by mockturtl** [mockturtl/cinnamon-weather#85]
@crosser writes: https://github.com/mockturtl/cinnamon-weather/issues/49#issuecomment-61058048

> when you specify a woeid that yahoo does not recognize, no useful diagnostic is produced, and the above errors are reported.
> 
> (And the page that opens on "Get WOEID" does not contain codes for my country.)

**Comment by mscheper** [comment]
Until this is fixed, what's the workaround for setting a WOEID? I've just upgraded to Mint 17.2 and I'm now experiencing [Issue 49](https://github.com/mockturtl/cinnamon-weather/issues/49) exactly, including '[I can't configure the applet... When I right-click the applet there is a Settings option, but that just takes me to the generic settings for all applets](https://github.com/mockturtl/cinnamon-weather/issues/49#issuecomment-24241175)'. (Strangely, the weather applet worked under Mint 14, and I'm pretty sure I needed to set a WOEID for that, too; I just can't remember how. I guess it's not stored in the home directory, or it would've survived the upgrade.)

**Comment by mockturtl** [comment]
> including 'I can't configure the applet... When I right-click the applet there is a Settings option

That option has [long been replaced](https://github.com/mockturtl/cinnamon-weather/blame/master/applet.js#L283) with Cinnamon's built-in "Configure" option.

![menu](https://cloud.githubusercontent.com/assets/705804/8783987/62b59f68-2eed-11e5-9a78-dc2ae1750847.jpg)

> I've just upgraded to Mint 17.2 [from Mint 14]

My guess is that your applet is badly out of date.  Try to remove and reinstall it _(Menu -> Applets)_.  (Failing that: delete the `~/.local/share/cinnamon/applets/weather@mockturtl` folder).  You'll have to re-configure your settings.

> I guess it's not stored in the home directory, or it would've survived the upgrade.

I believe that's correct.  Cinnamon stores this data ([gsettings](https://developer.gnome.org/gio/stable/gsettings-tool.html)?); you should not expect it to survive a system upgrade.

> Until this is fixed, what's the workaround for setting a WOEID?

You will need a WOEID.  Try <https://weather.codes/>.

**Comment by septhijssen** [comment]
In the meantime, since the applet still does not provide feedback about invalid WOEID codes, I would like to suggest 
http://iannuttall.co.uk/weather-location-codes/ 
as possibly better alternative to lookup weather location codes. I tested codes from this list for the Netherlands and for Ireland, and all of them seem to be working. Although the list
 https://weather.codes/
contains a lot more codes, it seems that almost all the extra codes (the ones not on http://iannuttall.co.uk/weather-location-codes/) are invalid.

Furthermore, as long as there is no feedback for invalid WOEIDs, may I suggest a warning on the 'Get WOEID' button. Perhaps change the button text in something like 
'Get WOEID (note that not every WOEID from this link is valid)'

**Comment by mockturtl** [comment]
Hello,

This issue is being closed because development is moving to [linuxmint/cinnamon-spices/applets](https://github.com/linuxmint/cinnamon-spices-applets).  Feel free to reopen your issue there.

Please see the release announcement here:

http://segfault.linuxmint.com/2017/01/changes-to-cinnamon-spices-for-developer-and-artists/
